# Descrição: Retorna todos os dados do conjunto em formato JSON.
# Funcionalidade: Listar todos os dados.
GET http://localhost:3000/

###

# Descrição: Retorna os dados do conjunto correspondentes ao ID informado em
# formato JSON.
# Funcionalidade: Listar os dados correspondentes ao ID.
GET http://localhost:3000/3

### 

# Descrição: Adiciona um novo dado ao conjunto.
# Funcionalidade: Adicionar novo dado.
POST http://localhost:3000/
Content-Type: application/json

{
  "id":"",
  "descricao": "Tênis NOVO Esportivo",
  "preco": 149.99,
  "cores": ["preto", "branco", "cinza", "azul"]
}



###
# Descrição: Atualiza os dados do conjunto correspondentes ao ID informado.
# Funcionalidade: Atualizar os dados correspondentes ao ID.

PUT http://localhost:3000/3
Content-Type: application/json

{
  "id":"3",
  "descricao": "Tênis NOVO Esportivo",
  "preco": 149.99,
  "cores": ["preto", "branco", "cinza", "azul"]
}

###

# Descrição: Remove os dados do conjunto correspondentes ao ID informado.
# Funcionalidade: Remover os dados correspondentes ao ID.
DELETE http://localhost:3000/2


